=== Sizeof Expressions

A *sizeof expression* is an expression that represents the size of a type.

==== Syntax

`sizeof(<<Type-Names,_type-name_>>)`

==== Semantics

The type name must <<Scoping-of-Names_Resolution-of-Qualified-Identifiers,refer to>>
a type that is <<Types_Displayable-Types, displayable>>.

The expression is evaluated by evaluating the maximum number of
bytes required to represent any value of that type. Evaluation
of type sizes is as follows:

* If the type name refers to a <<Types_Primitive-Integer-Types,primitive integer type>>
or <<Types_Floating-Point-Types,floating-point type>>, the size of the type is
the width of the representation in bytes.

* If the type name refers to a <<Types_The-Boolean-Type,Boolean type>>,
the size is 1 byte.

* If the type name refers to a <<Types_String-Types,string type>>, the 
size of the string is the maximum length of the string in bytes.

* If the type name refers to a <<Scoping-of-Names_Qualified-Identifiers,qualified identifier>>:

** If the qualified identifier refers to an <<Types_Alias-Types,alias type>>, 
the size of the alias type is the size of the underlying type.

** If the qualified identifier refers to an <<Types_Array-Types,array type>>,
the size of the array type is the size of the array element type multiplied 
by the number of element in the array.

** If the qualified identifier refers to an <<Types_Enum-Types,enum type>>,
the size of the enum type is the size of the representation type.

** If the qualified identifier refers to a <<Types_Struct-Types,struct type>>, 
the size of the struct type is the sum of all member type sizes.

==== Example

[source,fpp]
----
type T = U32
# sizeof(T) evaluates to 4
constant c = sizeof(T)

# sizeof(F64) evaluates to 8
constant c2 = sizeof(F64)

array A = [3] U16
# sizeof(A) evaluates to 6
constant c3 = sizeof(A)
----
